# This is a config that other dry-rb repositories use

sources:
  - repo: dry-rb/template-gem
    sync:
      - "!config.yml"
      - ".github/workflows/ci.yml.erb"
      - ".devtools/templates/*.sync:${{dir}}/${{name}}"
      - ".github/**/*.*"
      - "spec/*"
      - "*"
  - repo: action-hero/workflows
    sync:
      - ".github/workflows/*.yml"
