name: dry-validation
custom_ci: true
codacy_id: f30e3ff5ec304c55a73868cdbf055c67
gemspec:
  authors: ["Piotr Solnica"]
  email: ["piotr.solnica@gmail.com"]
  summary: "Validation library"
  files: ["config/*.yml"]
  development_dependencies:
    - bundler
    - rake
    - rspec
  runtime_dependencies:
    - [concurrent-ruby, "~> 1.0"]
    - [dry-core, "~> 0.5", ">= 0.5"]
    - [dry-container, "~> 0.7", ">= 0.7.1"]
    - [dry-initializer, "~> 3.0"]
    - [dry-schema, "~> 1.8", ">= 1.8.0"]
