# frozen_string_literal: true

# This file is synced from hanakai-rb/repo-sync

name: RuboCop

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUNDLE_ONLY: tools

    steps:
      - uses: actions/checkout@v3

      - name: Set up Ruby 3.4
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.4
          bundler-cache: true

      - name: Run RuboCop
        run: bundle exec rubocop --parallel
